# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MicrocksCli < Formula
  desc ""
  homepage "https://github.com/microcks/microcks-cli"
  version "0.5.8"

  on_macos do
    url "https://github.com/microcks/microcks-cli/releases/download/0.5.8/microcks-cli_0.5.8_darwin_all.tar.gz"
    sha256 "10ec55b1c7cad8e53aecf013851c771ddbeea418097b90d9527cd7c4b22e3a00"

    def install
      bin.install "microcks-cli"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/microcks/microcks-cli/releases/download/0.5.8/microcks-cli_0.5.8_linux_amd64.tar.gz"
        sha256 "f082bf11d65a3e4f00f0bf7eb9f0b1c42abd4a44f07569796fd1ba443b83e586"

        def install
          bin.install "microcks-cli"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/microcks/microcks-cli/releases/download/0.5.8/microcks-cli_0.5.8_linux_arm64.tar.gz"
        sha256 "2c8fd433f88aec0908b628f0476132a502eaf6b57e764317f5ee2b2f472ac755"

        def install
          bin.install "microcks-cli"
        end
      end
    end
  end
end
