# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MicrocksCli < Formula
  desc ""
  homepage "https://github.com/microcks/microcks-cli"
  version "0.5.7"

  on_macos do
    url "https://github.com/microcks/microcks-cli/releases/download/0.5.7/microcks-cli_0.5.7_darwin_all.tar.gz"
    sha256 "6665298691aeaff0fad023c49064e47c042ad09ab2d4ffe90b2ab751cc6a665a"

    def install
      bin.install "microcks-cli"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/microcks/microcks-cli/releases/download/0.5.7/microcks-cli_0.5.7_linux_amd64.tar.gz"
        sha256 "5b2ba64b97845b0606218ce9aab7bd6147272c5ddbab1a4608dec0d316828b12"

        def install
          bin.install "microcks-cli"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/microcks/microcks-cli/releases/download/0.5.7/microcks-cli_0.5.7_linux_arm64.tar.gz"
        sha256 "a0a24b9827283e5ad40c4c9bd50c8319d747cdae8071c8f17eb2bb3f96a774da"

        def install
          bin.install "microcks-cli"
        end
      end
    end
  end
end
