# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Microcks < Formula
  desc ""
  homepage "https://github.com/microcks/microcks-cli"
  version "0.9.0"

  on_macos do
    url "https://github.com/microcks/microcks-cli/releases/download/v0.9.0/microcks-cli_0.9.0_darwin_all.tar.gz"
    sha256 "f844846770dc9a61fa1aad43f78ecf7101768eb0f9fb08b8f8d316f7a5e8cb82"

    def install
      bin.install "microcks-cli"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/microcks/microcks-cli/releases/download/v0.9.0/microcks-cli_0.9.0_linux_amd64.tar.gz"
      sha256 "c5d9833775acc58dda588995244d3be867e99d4bbb3b3991716da49ae94da669"
      def install
        bin.install "microcks"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/microcks/microcks-cli/releases/download/v0.9.0/microcks-cli_0.9.0_linux_arm64.tar.gz"
      sha256 "cf17b5daf950c176fa4a0aac42f3f639648692cf2eac32dc987084947221490d"
      def install
        bin.install "microcks"
      end
    end
  end
end
