# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Microcks < Formula
  desc ""
  homepage "https://github.com/microcks/microcks-cli"
  version "1.0.3"

  on_macos do
    url "https://github.com/microcks/microcks-cli/releases/download/1.0.3/microcks-cli_1.0.3_darwin_all.tar.gz"
    sha256 "63dd8a17941590e1bf93babf6f8290ddff2adac539ea89a74302ed37ac3eeb70"

    define_method(:install) do
      bin.install "microcks"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/microcks/microcks-cli/releases/download/1.0.3/microcks-cli_1.0.3_linux_amd64.tar.gz"
      sha256 "a73fbda72ec3c8856c4a624ae1f34a5a5193df31cbc8178d4158cde4a01145dd"
      define_method(:install) do
        bin.install "microcks"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/microcks/microcks-cli/releases/download/1.0.3/microcks-cli_1.0.3_linux_arm64.tar.gz"
      sha256 "7f37cd6b21d33fb3413945c18185f48a774eb73293d892fe21bc5d2f20de5bc2"
      define_method(:install) do
        bin.install "microcks"
      end
    end
  end
end
