# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Microcks < Formula
  desc ""
  homepage "https://github.com/microcks/microcks-cli"
  version "1.0.2"

  on_macos do
    url "https://github.com/microcks/microcks-cli/releases/download/1.0.2/microcks-cli_1.0.2_darwin_all.tar.gz"
    sha256 "c0d0ede140eb14cff1139945c8787976a52267783a3cc535c84d152c865f8eab"

    def install
      bin.install "microcks"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/microcks/microcks-cli/releases/download/1.0.2/microcks-cli_1.0.2_linux_amd64.tar.gz"
      sha256 "0b84bdb3faa15c42f01092a0a80bc1c91fc0d0f75849f4ccfc875bd3051ae268"
      def install
        bin.install "microcks"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/microcks/microcks-cli/releases/download/1.0.2/microcks-cli_1.0.2_linux_arm64.tar.gz"
      sha256 "078f8da1b6cc6efa90a59a12883fd35b075b85975c9bea3686fa2536983b549d"
      def install
        bin.install "microcks"
      end
    end
  end
end
